# Generated by Django 4.2.3 on 2023-07-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('biography', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, default='app/img/not_avalaible.png', upload_to='authors')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Enter a brief description of the book')),
                ('book_text', models.FileField(upload_to='books/')),
                ('cover', models.ImageField(blank=True, default='app/img/not_avalaible.png', upload_to='covers/')),
                ('genre', models.CharField(blank=True, max_length=50)),
                ('isbn', models.CharField(blank=True, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('author', models.ManyToManyField(to='app.author')),
            ],
        ),
    ]
